global:
  resolve_timeout: 1m
route:
  receiver: 'default'
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h
receivers:
  - name: 'default'
    email_configs:
      - to: 'email@email.com'
        send_resolved: true
